- name: Update DNS and NTP
  hosts: all
  become: yes
  vars:
    resolf_conf_path: /etc/resolv.conf
    chrony_conf_path: /etc/chrony.conf
    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
    ntp_servers:
      - time1.google.com
      - time2.google.com

  tasks:
    - name: Update {{ resolf_conf_path }}
      lineinfile:
        dest: "{{ resolf_conf_path }}"
        line: "nameserver {{ dns_server }}"
      with_items: "{{ dns_servers }}"
      loop_control:
        loop_var: dns_server

    - name: Update {{ chrony_conf_path }}
      lineinfile:
        dest: "{{ chrony_conf_path }}"
        line: "server {{ ntp_server }} iburst"
      with_items: "{{ ntp_servers }}"
      loop_control:
        loop_var: ntp_server
